### ISSUE TITLE
Property List Bug

### ISSUE THREAD

**Issue by bfrisoni** [Kobee1203/jcrom#111]
When an entity has a List<String> property, if it is not populated you will get a Exception on creation of the node.
org.jcrom.JcrMappingException: Could not create node from object
cause:
javax.jcr.ItemNotFoundException: Cannot remove a non-existing property.

So I tried setting the List<String> property to an empty list and now I got this exception:
javax.jcr.nodetype.ConstraintViolationException: no matching property definition found.

I am using 
jcrom v2.1.0
jackrabbit v2.6.5

**Comment by Kobee1203** [comment]
fixed

**Comment by bfrisoni** [comment]
Glad you were able to use the patch.

Cheers.
