### ISSUE TITLE
JcrProperty being mapped to a List<String> is returning null when the list only has one item.

### ISSUE THREAD

**Issue by Kobee1203** [Kobee1203/jcrom#115]
Reported by araujocarlos (https://code.google.com/u/113710422720530663285/), Jun 26 (3 days ago)
What steps will reproduce the problem?
1. List<String> property mapped with JcrProperty
2. Retrieve from JCR node that has only one item in list property
3. Null is populated as value

What is the expected output? What do you see instead?
I am expecting to get a list of one item. I am getting a null instead. If the JCR property has two or more items the property works well.

What version of the product are you using? On what operating system?
2.2.0

**Comment by frankgh** [comment]
ac9e4897b2666970d165b1eaf16df16d4d908c4a

**Comment by frankgh** [comment]
Fixed
