### ISSUE TITLE
Invalid artifact descriptor for org.jcrom:jcrom:jar:2.2.0

### ISSUE THREAD

**Issue by lucasweb78** [Kobee1203/jcrom#126]
WARNING: Invalid artifact descriptor for org.jcrom:jcrom:jar:2.2.0: 1 problem was encountered while building the effective model for org.jcrom:jcrom:2.2.0
[ERROR] 'dependencies.dependency.systemPath' for com.oracle:javafx:jar must specify an absolute path but is ${javafx.rt.jar} @

**Comment by amischler** [comment]
You should define a javafx.rt.jar property as explained here : [http://notaboekje.blogspot.fr/2012/02/creer-un-projet-maven-pour-javafx.html](http://notaboekje.blogspot.fr/2012/02/creer-un-projet-maven-pour-javafx.html)

Note : this dependency to the javafx jar can be safely removed with Java 8, this trick was only required with Java 7.

**Comment by lucasweb78** [comment]
I am using Java 8, how can I remove the dependency to the javafx jar? I have tried excluding it in my pom.xml but still see the error.
